Added Azure-specific page and corrected some typos
1. Added Azure page.
2. Corrected some typos on the Google page.

I updated the glooctl example to use `--release` because the bare
command returned:

```
Error: installing gloo in gateway mode: you must provide a file or a release version containing the manifest when running an unreleased version of glooctl.
```